### ISSUE TITLE
timewarrior zsh plugin

### ISSUE THREAD

**Issue by svenXY** [lauft/timew-bashcompletion#1]
Hi,

not an issue, just a heads-up - I've taken the liberty to use your completion script and make it into a zsh plugin suitable for oh-my-zsh, zgen and the like.

You can find it here:
https://github.com/svenXY/timewarrior

Thanks for your great work!

Cheers,
Sven

**Comment by lauft** [comment]
Thanks a lot for your contribution!
I hope in the near future these get nicely documented on the website and bundled up in the release tarballs.
