### ISSUE TITLE
Regression: can't complete tags properly if there is a tag description

### ISSUE THREAD

**Issue by nodens** [lauft/timew-bashcompletion#8]
Hi,

#2 introduced a regression: whenever a tag has a description, since there is no way to separate the description from the tag in the output, the proposed completion is something like `"<tag> \ \ \ \ \ <desc>"`

If we want both support for spaces in tags and tags with description, until #3 is fixed, either we directly extract the list from `~/timewarrior/tags` (but that would need a dependancy on jq or something), or the modification has to be done on timewarrior side: like, allow listing tags without description with a switch, or adding a separator (| or whatever) in `timew tags` output.

Of course, since a modification is needed on timewarrior, then the best would be to fix GothenburgBitFactory/timewarrior#188 (sadly that's beyond me ;) )

What do you think ?

**Comment by lauft** [comment]
Currently Timewarrior does not support description in tags, so this issue is no regression but rather hypothetical (The description is always "-" with past and current versions).

https://github.com/GothenburgBitFactory/timewarrior/issues/188 (scheduled for the 1.4.0 milestone) is definitely going to be implemented before support of tag descriptions.

**Comment by nodens** [comment]
OK, I get it's not considered a complete feature, but I do have descriptions in my tags… I added them using 
tags.<tag>.description in configuration, as described in https://timewarrior.net/docs/tutorial.html.
The completion is apparently the only place where it is an issue, so far.


```
nodens@shadowfax:~$ timew tags

Tag                     Description                                
admin                 Generic: Admin, Billing, Project Management
aa                       Client: AA (bb Group)
aa_infra              AA: infra
invoiced              Generic: Invoice sent
xx                        Client: XX
xx_addressplan   xx : Address Plan
xx_cloud             Client xx: Cloud project
coolproject                 -
```

(edited for privacy)

**Comment by lauft** [comment]
@nodens You are right, I missed this - sorry. 😞 

I have pushed a small change that will delete everything after a "-" in the tags listing. If you add a "-" to your tag descriptions, bash completion should hopefully work again for you (and break it for everyone who uses hyphens in tags...)

This is just a quick and dirty workaround until https://github.com/GothenburgBitFactory/timewarrior/issues/188 is implemented!

**Comment by nodens** [comment]
So I made a few modifications to sed command line. It requires that you prefix the descriptions by `-%` but it works nicely apart from that. For me it does, at least, until timewarrior 1.4 is out :)

**Comment by lauft** [comment]
I've merged your PR.

Btw: https://github.com/GothenburgBitFactory/timewarrior/issues/188 is is making good progress... 😉
